apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todolist-deploy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ssehnem/todolist.git
    targetRevision: HEAD
    path: devops-k8s/manifests/
    directory:
      exclude: '{package.json,README.md, Dockerfile}'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
